apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gloo-ui-gateway
  namespace: istio-gateways
spec:
  gatewayClassName: istio
  listeners:
  - name: https
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
        - name: my-tls-secret
          kind: Secret
          namespace: istio-gateways
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: gloo-ui-httproute
  namespace: gloo-mesh
spec:
  parentRefs:
    - name: gloo-ui-gateway
      namespace: istio-gateways
  rules:
    - backendRefs:
        - name: gloo-mesh-ui
          namespace: gloo-mesh
          port: 8090
      matches:
        - path:
            type: PathPrefix
            value: /