base: |
  global:
    istioNamespace: istio-system
  profile: ambient
  revision: gloo
cni: |
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  cni:
    ambient:
      dnsCapture: true
    cniBinDir: /home/kubernetes/bin
  global:
    istioNamespace: istio-system
    logAsJson: true
    variant: distroless
  profile: ambient
  revision: gloo
istiod: |
  env:
    REQUIRE_3P_TOKEN: false
    extensionProviders:
    - envoyOtelAls:
        port: "4317"
        service: gloo-telemetry-collector-testing.gloo-mesh.svc.cluster.local
  global:
    istioNamespace: istio-system
    logAsJson: true
    meshID: cluster1
    multiCluster:
      clusterName: cluster1
    network: cluster1
    variant: distroless
  license:
    value: eyJleHAiOjI0OTAzODM0NjYsImlhdCI6MTYyNjQ2OTg2NiwiayI6IlpuelRaUSIsImx0IjoiZW50IiwicHJvZHVjdCI6Imdsb28tbWVzaC1nYXRld2F5In0.aXJ1H9FG3gub5gGYI1XAXECpzbzVfxVWA5L9C4WLKNE
  meshConfig:
    accessLogEncoding: JSON
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
      tracing:
        custom_tags:
          clusterID:
            environment:
              name: ISTIO_META_CLUSTER_ID
        max_path_tag_length: 256
    enableTracing: false
    extensionProviders:
    - envoyOtelAls:
        port: "4317"
        service: gloo-telemetry-collector.gloo-mesh.svc.cluster.local
      name: envoyOtelAls
    - envoyFileAccessLog:
        path: /dev/stdout
      name: envoy
    trustDomain: cluster1
  pilot:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: istio.io/rev
                operator: In
                values:
                - gloo
            topologyKey: topology.kubernetes.io/zone
          weight: 100
    autoscaleEnabled: true
    autoscaleMax: 25
    autoscaleMin: 2
    cpu:
      targetAverageUtilization: 80
    env:
      AUTO_RELOAD_PLUGIN_CERTS: "true"
      PILOT_ENABLE_IP_AUTOALLOCATE: "true"
      PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: "true"
      PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS: "true"
      PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
  platforms:
    peering:
      enabled: true
  profile: ambient
  revision: gloo
  revisionTags:
  - default
ztunnel: |
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/compute-type
            operator: NotIn
            values:
            - fargate
  env:
    ISTIO_META_DNS_CAPTURE: "true"
    SKIP_VALIDATE_TRUST_DOMAIN: "true"
  istioNamespace: istio-system
  logAsJson: true
  multiCluster:
    clusterName: cluster1
  network: cluster1
  profile: ambient
  revision: gloo