apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: httpbin-external-service
  namespace: bookinfo
spec:
  hosts:
  - httpbin.org
  ports:
  - number: 80
    name: http
    protocol: TCP
  resolution: DNS